// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwytkzzzvtdwsscmxqgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13eXRrenp6dnRkd3NzY214cWdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1OTY0NjYsImV4cCI6MjA1ODE3MjQ2Nn0.oOPdN64DZ922AaKoboxPrewrETh9MbAygoH5EooVk_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);